version: '3.8'

services:
  mongodbHabit:
    image: mongo:latest
    container_name: mongodbHabit
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: habits
    restart: unless-stopped

  javaapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: javaapp
    ports:
      - "8089:8089"
    depends_on:
      - mongodbHabit
    environment:
      MONGO_URI: mongodb://root:example@mongodbHabit:27017/habits?authSource=admin
    restart: unless-stopped


volumes:
  mongodb_data: